### ISSUE TITLE
Plural removal affects entity id and count, not just display

### ISSUE THREAD

**Issue by make-all** [Petro31/ad_people_tracker#2]
My family has two phones, which have identites device_tracker.galaxy-a20 and device_tracker.galaxy-a20s.  When both these devices are home, the count is off by one, and only the former reported as home.

I'd expect plural removal to only affect the name displayed, not for the separate entities to be deduplicated when counting.

**Comment by Petro31** [comment]
Can you post your configurations?

**Comment by make-all** [comment]
I've since renamed one of the phones now that I've identified the issue to work around the problem, but the original configuration was:

people_at_home:
   module: people_tracker
   class: PeopleTracker
   guest_entity_id: input_boolean.guests
   entities:
     - device_tracker.jasons_mobile
     - device_tracker.galaxy_a20s
     - device_tracker.galaxy_a20
