### ISSUE TITLE
Setup Description

### ISSUE THREAD

**Issue by LordNex** [Petro31/ad_people_tracker#3]
I came across this and figured I'd give it a try. But the setup description doesn't explain much. I have it installed via HACS but where do I add the config?  Should this be in my configuration.yaml, apps.yaml, or somewhere else?

Also, my understanding is that it will pull any device connected to my WiFi that's mobile? Or how is it determining which devices to display?

**Comment by Petro31** [comment]
This is an AppDaemon app.  Are you using AppDaemon?

**Comment by LordNex** [comment]
> This is an AppDaemon app.  Are you using AppDaemon?

Yes. I was able to get it to work but it would probably help if you add that the config values need added to apps.yaml. There are still a lot of AppDaemon newbies like me out there that it doesn't immediately sink in with. 

I was able to get it to track the 3 people in my home, I'll have to test how it acts the next time someone other comes by. But the one issue I am having is that the font size for the entity listed as an "and" "or" list cuts off the names. I tried several different ways to add it to Lovelace but couldn't get it to stop cutting off the text. I'm wanting to have a card with a name like "Who's at Home" and it then list by name everyone who's currently home. Hopefully that makes sense. But I'm not sure if there is a way to change the font size.

**Comment by Petro31** [comment]
> Yes. I was able to get it to work but it would probably help if you add that the config values need added to apps.yaml. There are still a lot of AppDaemon newbies like me out there that it doesn't immediately sink in with.

I'm not sure what you mean?  I have examples and a full description in the readme.

https://github.com/Petro31/ad_people_tracker

![image](https://user-images.githubusercontent.com/35082313/97358251-5ddbf780-1871-11eb-8b0c-6fdd284b794e.png)

**Comment by LordNex** [comment]
It doesn't really explain that you need to manually create the helper for input_boolean.guests 

Took me a bit to see in the logs and create. Not probably people would normally check

It also doesn't explain how to use it well. I understand that the guests is an input Boolean. But what would I use that for. Just a sensor for when someone else besides my family connects to my network? Or does it detect "rouge" devices is range without them having to connect? 

I do have the People at Home sensor setup and like it. But do you know of a way to make it say "Empty" or something else besides "Unavailable" when no ones home. Been trying to figure a way to do it but haven't yet. Thanks for the hard work man. Very cool add on 👍

**Comment by Petro31** [comment]
The 'requiring guests' is a bug and logged as a separate issue.  It shouldn't be required.

The guests is to truncate the state and list other people without listing other people.  States in home assistant are limited to 254 characters.  This was a way to mitigate that.  Also, I made this for notifications for my phone.  I didn't want a list of 900 devices in my message.  It does not detect rogue devices.  It's up to the user to maintain the 'guests' toggle.

When no one is at home, it should read zero.

**Comment by LordNex** [comment]
Ok that’s cool. Maybe I was assuming it did more that it does. Would be cool if it could pick that up but you’d have to find a way to filter the list to only detect certain types of devices. I might play around with it and see what I can do but doubt I’ll probably use it.

As far as the “Unavailable”. The badge icon shows 0 correctly. But if I add a card that lists the names of who’s home, and no one is, is shows as “Unavailable”. Sorry if I didn’t make that clear before.

Benjamin Powers

On Nov 25, 2020, at 8:33 AM, Petro31 <notifications@github.com> wrote:

﻿

The 'requiring guests' is a bug and logged as a separate issue. It shouldn't be required.

The guests is to truncate the state and list other people without listing other people. States in home assistant are limited to 254 characters. This was a way to mitigate that. Also, I made this for notifications for my phone. I didn't want a list of 900 devices in my message. It does not detect rogue devices. It's up to the user to maintain the 'guests' toggle.

When no one is at home, it should read zero.
