### ISSUE TITLE
Module won't work

### ISSUE THREAD

**Issue by samchan88** [Petro31/ad_people_tracker#4]
AppDaemon 4 version 0.8.0 will break this module and this module will not work properly anymore.
Hope you will resolve this issue.
Thank you.

**Comment by Petro31** [comment]
I don't use appdeamon anymore and I moved to a template sensor for this.  How is appdeamon changing so that this doesn't work?

This template sensor does the exact same thing without the need for appdaemon
```
- sensor:
  - unique_id: people_at_home
    name: People at Home
    state: >
      {%- set people = expand('group.people') %}
      {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count }}
    icon: >
      {%- set icons = ['account-off', 'account', 'account-multiple'] %}
      {%- set people = expand('group.people') %}
      {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count %}
      {%- if cnt >= 0 %}
        mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
      {%- else %}
        mdi:account-alert
      {%- endif %}
    attributes:
      template: people_tracker
      people: > 
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people }}
      and: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      or: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      count: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people | count }}
```

**Comment by LordNex** [comment]
Yea I’ve been running this for 3 year or so now and haven’t had one problem. All my software is at the latest current stable version and it’s still working.


On Jan 10, 2022, at 7:12 AM, Petro31 ***@***.***> wrote:

﻿

I don't use appdeamon anymore and I moved to a template sensor for this. How is appdeamon changing so that this doesn't work?

This template sensor does the exact same thing without the need for appdaemon

- sensor:
  - unique_id: people_at_home
    name: People at Home
    state: >
      {%- set people = expand('group.people') %}
      {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count }}
    icon: >
      {%- set icons = ['account-off', 'account', 'account-multiple'] %}
      {%- set people = expand('group.people') %}
      {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count %}
      {%- if cnt >= 0 %}
        mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
      {%- else %}
        mdi:account-alert
      {%- endif %}
    attributes:
      template: people_tracker
      people: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people }}
      and: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      or: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      count: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people | count }}

**Comment by make-all** [comment]
I'm also seeing a problem after updating AppDaemon at the weekend. It seems to be counting people multiple times.
I guess I'll try the template.  It looks like I need to set up a group containing the people I want to track plus the guest switch, is that correct?

Edit: it is not counting people multiple times, it is counting boolean entities that go unavailable then available again even when they do not match any of the entities that are configured for tracking.  The main offender seems to be Light entities from the browser_mod custom integration, but I just had one of my smart switches get added to the count as well after it went offline breifly.

**Comment by make-all** [comment]
FWIW, I think the cause is this change in AppDaemon 4.2.0 from the Breaking Changes section:

- Changed set_state and listen_state to support entity_id and not entity, to standardise use across api calls

**Comment by samchan88** [comment]
> I don't use appdeamon anymore and I moved to a template sensor for this. How is appdeamon changing so that this doesn't work?
> 
> This template sensor does the exact same thing without the need for appdaemon
> 
> ```
> - sensor:
>   - unique_id: people_at_home
>     name: People at Home
>     state: >
>       {%- set people = expand('group.people') %}
>       {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count }}
>     icon: >
>       {%- set icons = ['account-off', 'account', 'account-multiple'] %}
>       {%- set people = expand('group.people') %}
>       {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count %}
>       {%- if cnt >= 0 %}
>         mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
>       {%- else %}
>         mdi:account-alert
>       {%- endif %}
>     attributes:
>       template: people_tracker
>       people: > 
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
>         {%- set people = people + company %}
>         {{ people }}
>       and: >
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
>         {%- set people = people + company %}
>         {%- if people | count > 0 %}
>           {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
>         {%- else %}unknown
>         {%- endif %}
>       or: >
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
>         {%- set people = people + company %}
>         {%- if people | count > 0 %}
>           {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
>         {%- else %}unknown
>         {%- endif %}
>       count: >
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
>         {%- set people = people + company %}
>         {{ people | count }}
> ```

I'm using your App in a couple of my automations (an example is to auto arm my alarm system when people count becomes zero). I do not know how to make it a routine and thus might means I will copy the same codes to various location making it difficult for maintenance. Anyway, thanks.

**Comment by samchan88** [comment]
> FWIW, I think the cause is this change in AppDaemon 4.2.0 from the Breaking Changes section:
> 
> * Changed set_state and listen_state to support entity_id and not entity, to standardise use across api calls

You are right. Your solution works. Thank you.

**Comment by LordNex** [comment]
Thanks for the idea 💡

Don’t know why but I’m not having the same issue as you guys. Mines still working fine. But I track the person entity and not the device. That way I can easily swap devices or whatever and not have to update that part of the app. I keep a badge on the top of my page that keeps a numbered count of how many people are home. I then also have each member of my family in a badge with their location below. I’ve also created zones for the most common places we all frequent.

Where are you guys running into issues? Are there any logs you could provide that might point a direction?

Benjamin T Powers

On Jan 10, 2022, at 11:10 PM, samchan88 ***@***.***> wrote:

﻿

I don't use appdeamon anymore and I moved to a template sensor for this. How is appdeamon changing so that this doesn't work?

This template sensor does the exact same thing without the need for appdaemon

- sensor:
  - unique_id: people_at_home
    name: People at Home
    state: >
      {%- set people = expand('group.people') %}
      {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count }}
    icon: >
      {%- set icons = ['account-off', 'account', 'account-multiple'] %}
      {%- set people = expand('group.people') %}
      {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count %}
      {%- if cnt >= 0 %}
        mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
      {%- else %}
        mdi:account-alert
      {%- endif %}
    attributes:
      template: people_tracker
      people: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people }}
      and: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      or: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      count: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set people = people + company %}
        {{ people | count }}


I'm using your App in a couple of my automations (an example is to auto arm my alarm system when people count becomes zero). I do not know how to make it a routine and thus might means I will copy the same codes to various location making it difficult for maintenance. Anyway, thanks.

**Comment by Petro31** [comment]
> 

what issues?  Are there errors in the logs?  From what I remember, it'll only count unqiue people.

As for the template, what you do is you make the people in home assitant by attaching all the device trackers to the people.  Then, make a group of the people that you want to track home/away on.  Name the group `people`.

The template will work out of the box.  You can add a guest input_boolean to the list of people and it will treat that like a person as well.  Guest will always be the last person in the sensor.

**Comment by kaizersoje** [comment]
Posting the template sensor with the guests `input_boolean`
```
- sensor:
  - unique_id: people_at_home
    name: People at Home
    state: >
      {%- set people = expand('group.people') %}
      {%- set guests = iif(is_state('input_boolean.guests', 'on'), 1, 0) %}
      {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count + guests }}
    icon: >
      {%- set icons = ['account-off', 'account', 'account-multiple'] %}
      {%- set people = expand('group.people') %}
      {%- set guests = iif(is_state('input_boolean.guests', 'on'), 1, 0) %}
      {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count + guests %}
      {%- if cnt >= 0 %}
        mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
      {%- else %}
        mdi:account-alert
      {%- endif %}
    attributes:
      template: people_tracker
      people: > 
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
        {%- set people = people + company + guests  %}
        {{ people }}
      and: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
        {%- set people = people + company + guests  %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      or: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
        {%- set people = people + company + guests  %}
        {%- if people | count > 0 %}
          {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
        {%- else %}unknown
        {%- endif %}
      count: >
        {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
        {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
        {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
        {%- set people = people + company + guests  %}
        {{ people | count }}
```

**Comment by Petro31** [comment]
> Posting the template sensor with the guests `input_boolean`
> 
> ```
> 
> - sensor:
> 
>   - unique_id: people_at_home
> 
>     name: People at Home
> 
>     state: >
> 
>       {%- set people = expand('group.people') %}
> 
>       {%- set guests = iif(is_state('input_boolean.guests', 'on'), 1, 0) %}
> 
>       {{ people | selectattr('state', 'in', ['home', 'on'] ) | list | count + guests }}
> 
>     icon: >
> 
>       {%- set icons = ['account-off', 'account', 'account-multiple'] %}
> 
>       {%- set people = expand('group.people') %}
> 
>       {%- set guests = iif(is_state('input_boolean.guests', 'on'), 1, 0) %}
> 
>       {%- set cnt = people | selectattr('state', 'in', ['home', 'on'] ) | list | count + guests %}
> 
>       {%- if cnt >= 0 %}
> 
>         mdi:{{ icons[cnt] if cnt in range(icons | count) else 'account-group' }}
> 
>       {%- else %}
> 
>         mdi:account-alert
> 
>       {%- endif %}
> 
>     attributes:
> 
>       template: people_tracker
> 
>       people: > 
> 
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
> 
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
> 
>         {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
> 
>         {%- set people = people + company + guests  %}
> 
>         {{ people }}
> 
>       and: >
> 
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
> 
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
> 
>         {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
> 
>         {%- set people = people + company + guests  %}
> 
>         {%- if people | count > 0 %}
> 
>           {{- [people[:-1] | join(', '), 'and', people[-1]] | join(' ') if people | count > 1 else people[0] }}
> 
>         {%- else %}unknown
> 
>         {%- endif %}
> 
>       or: >
> 
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
> 
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
> 
>         {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
> 
>         {%- set people = people + company + guests  %}
> 
>         {%- if people | count > 0 %}
> 
>           {{- [people[:-1] | join(', '), 'or', people[-1]] | join(' ') if people | count > 1 else people[0] }}
> 
>         {%- else %}unknown
> 
>         {%- endif %}
> 
>       count: >
> 
>         {%- set people = expand('group.people') | selectattr('state', 'eq', 'home') | map(attribute='name') | list %}
> 
>         {%- set company = expand('group.people') | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
> 
>         {%- set guests = iif(is_state('input_boolean.guests', 'on'), ['Guests'], []) %}
> 
>         {%- set people = people + company + guests  %}
> 
>         {{ people | count }}
> 
> ```

The template already handled that, you just doubled the logic.  All you had to do was add the input boolean to the group of people.

**Comment by kaizersoje** [comment]
Ohh oops my bad. Thanks.
